services:
  # الباك إند
  - type: web
    name: iqrani-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # الفرونت إند
  - type: web
    name: iqrani-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm install -g react-scripts
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://iqrani-backend.onrender.com/api 