services:
  # الباك إند
  - type: web
    name: iqrani-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://iqrani:iqrani@omar$$$inshaallah@iqrani.ii5gi.mongodb.net/iqrani?retryWrites=true&w=majority
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # الفرونت إند
  - type: web
    name: iqrani-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm install @babel/plugin-proposal-private-property-in-object --save-dev
      npm install eslint-config-react-app --save-dev
      npm install react-scripts --save
      chmod +x node_modules/.bin/react-scripts
      CI=false npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://iqrani-backend.onrender.com/api 